/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Announcement {
  'id' : string,
  'title' : string,
  'content' : string,
  'scheduledTime' : [] | [Time],
  'published' : boolean,
  'image' : [] | [ExternalBlob],
  'targetSegment' : string,
}
export interface CoachNote {
  'id' : string,
  'memberId' : string,
  'content' : string,
  'timestamp' : Time,
}
export type ConsentStatus = { 'active' : null } |
  { 'pending' : null } |
  { 'optedOut' : null };
export interface DailyCheckin {
  'id' : string,
  'memberId' : string,
  'waterIntake' : number,
  'date' : Time,
  'digestionScore' : bigint,
  'steps' : bigint,
  'notes' : [] | [string],
  'moodScore' : bigint,
  'workoutMinutes' : bigint,
  'complianceScore' : bigint,
  'sleepHours' : number,
}
export type ExternalBlob = Uint8Array;
export interface FollowupTask {
  'id' : string,
  'status' : TaskStatus,
  'memberId' : string,
  'completionDate' : [] | [Time],
  'dueDate' : Time,
  'description' : string,
  'coachNoteId' : [] | [string],
}
export type Gender = { 'other' : null } |
  { 'female' : null } |
  { 'male' : null };
export interface MemberProfile {
  'id' : string,
  'age' : bigint,
  'trfWindowEnd' : [] | [Time],
  'consentStatus' : ConsentStatus,
  'heightCm' : number,
  'lastWeightUpdate' : [] | [Time],
  'name' : string,
  'consentTimestamp' : [] | [Time],
  'noSnacks' : boolean,
  'reminderPreference' : ReminderPreference,
  'startingWeight' : number,
  'waistCircumference' : [] | [number],
  'targetDate' : [] | [Time],
  'chestCircumference' : [] | [number],
  'gender' : Gender,
  'targetWeight' : [] | [number],
  'programType' : string,
  'hipCircumference' : [] | [number],
  'trfWindowStart' : [] | [Time],
  'whatsappPhone' : string,
  'currentWeight' : number,
}
export interface MessageLog {
  'id' : string,
  'status' : string,
  'memberId' : string,
  'templateId' : string,
  'timestamp' : Time,
  'providerMessageId' : [] | [string],
}
export type ReminderPreference = { 'both' : null } |
  { 'none' : null } |
  { 'daily' : null } |
  { 'weekly' : null };
export interface SwitchMemberInput { 'whatsappPhone' : string }
export type TaskStatus = { 'completed' : null } |
  { 'dueToday' : null } |
  { 'overdue' : null };
export type Time = bigint;
export interface UpdateWeightInput { 'memberId' : string, 'newWeight' : number }
export interface UserProfile {
  'memberId' : [] | [string],
  'name' : string,
  'role' : UserRole,
}
export type UserRole = { 'member' : null } |
  { 'assistantCoach' : null } |
  { 'coach' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WeeklyCheckin {
  'id' : string,
  'hip' : [] | [number],
  'weight' : number,
  'memberId' : string,
  'date' : Time,
  'chest' : [] | [number],
  'wins' : [] | [string],
  'struggles' : [] | [string],
  'waist' : [] | [number],
  'photos' : [] | [ExternalBlob],
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCoachNote' : ActorMethod<[CoachNote], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'completeTask' : ActorMethod<[string], undefined>,
  'createAnnouncement' : ActorMethod<[Announcement], undefined>,
  'createFollowupTask' : ActorMethod<[FollowupTask], undefined>,
  'createMemberProfile' : ActorMethod<[MemberProfile], undefined>,
  'getAllAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'getAllCoachNotes' : ActorMethod<[], Array<CoachNote>>,
  'getAllDailyCheckins' : ActorMethod<[], Array<DailyCheckin>>,
  'getAllFollowupTasks' : ActorMethod<[], Array<FollowupTask>>,
  'getAllMembers' : ActorMethod<[], Array<MemberProfile>>,
  'getAllMessageLogs' : ActorMethod<[], Array<MessageLog>>,
  'getAllWeeklyCheckins' : ActorMethod<[], Array<WeeklyCheckin>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getMemberProfile' : ActorMethod<[string], MemberProfile>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logMessage' : ActorMethod<[MessageLog], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitDailyCheckin' : ActorMethod<[DailyCheckin], undefined>,
  'submitWeeklyCheckin' : ActorMethod<[WeeklyCheckin], undefined>,
  'switchMember' : ActorMethod<[SwitchMemberInput], [] | [UserProfile]>,
  'updateCurrentWeight' : ActorMethod<[UpdateWeightInput], undefined>,
  'updateMemberProfile' : ActorMethod<[string, MemberProfile], undefined>,
  'updateTaskStatus' : ActorMethod<[string, TaskStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];