/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const CoachNote = IDL.Record({
  'id' : IDL.Text,
  'memberId' : IDL.Text,
  'content' : IDL.Text,
  'timestamp' : Time,
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Announcement = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'scheduledTime' : IDL.Opt(Time),
  'published' : IDL.Bool,
  'image' : IDL.Opt(ExternalBlob),
  'targetSegment' : IDL.Text,
});
export const TaskStatus = IDL.Variant({
  'completed' : IDL.Null,
  'dueToday' : IDL.Null,
  'overdue' : IDL.Null,
});
export const FollowupTask = IDL.Record({
  'id' : IDL.Text,
  'status' : TaskStatus,
  'memberId' : IDL.Text,
  'completionDate' : IDL.Opt(Time),
  'dueDate' : Time,
  'description' : IDL.Text,
  'coachNoteId' : IDL.Opt(IDL.Text),
});
export const ConsentStatus = IDL.Variant({
  'active' : IDL.Null,
  'pending' : IDL.Null,
  'optedOut' : IDL.Null,
});
export const ReminderPreference = IDL.Variant({
  'both' : IDL.Null,
  'none' : IDL.Null,
  'daily' : IDL.Null,
  'weekly' : IDL.Null,
});
export const Gender = IDL.Variant({
  'other' : IDL.Null,
  'female' : IDL.Null,
  'male' : IDL.Null,
});
export const MemberProfile = IDL.Record({
  'id' : IDL.Text,
  'age' : IDL.Nat,
  'trfWindowEnd' : IDL.Opt(Time),
  'consentStatus' : ConsentStatus,
  'heightCm' : IDL.Float64,
  'name' : IDL.Text,
  'consentTimestamp' : IDL.Opt(Time),
  'noSnacks' : IDL.Bool,
  'reminderPreference' : ReminderPreference,
  'startingWeight' : IDL.Float64,
  'waistCircumference' : IDL.Opt(IDL.Float64),
  'targetDate' : IDL.Opt(Time),
  'chestCircumference' : IDL.Opt(IDL.Float64),
  'gender' : Gender,
  'targetWeight' : IDL.Opt(IDL.Float64),
  'programType' : IDL.Text,
  'hipCircumference' : IDL.Opt(IDL.Float64),
  'trfWindowStart' : IDL.Opt(Time),
  'whatsappPhone' : IDL.Text,
  'currentWeight' : IDL.Float64,
});
export const DailyCheckin = IDL.Record({
  'id' : IDL.Text,
  'memberId' : IDL.Text,
  'waterIntake' : IDL.Float64,
  'date' : Time,
  'digestionScore' : IDL.Nat,
  'steps' : IDL.Nat,
  'notes' : IDL.Opt(IDL.Text),
  'moodScore' : IDL.Nat,
  'workoutMinutes' : IDL.Nat,
  'complianceScore' : IDL.Nat,
  'sleepHours' : IDL.Float64,
});
export const MessageLog = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'memberId' : IDL.Text,
  'templateId' : IDL.Text,
  'timestamp' : Time,
  'providerMessageId' : IDL.Opt(IDL.Text),
});
export const WeeklyCheckin = IDL.Record({
  'id' : IDL.Text,
  'hip' : IDL.Opt(IDL.Float64),
  'weight' : IDL.Float64,
  'memberId' : IDL.Text,
  'date' : Time,
  'chest' : IDL.Opt(IDL.Float64),
  'wins' : IDL.Opt(IDL.Text),
  'struggles' : IDL.Opt(IDL.Text),
  'waist' : IDL.Opt(IDL.Float64),
  'photos' : IDL.Opt(ExternalBlob),
});
export const UserRole = IDL.Variant({
  'member' : IDL.Null,
  'assistantCoach' : IDL.Null,
  'coach' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'memberId' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'role' : UserRole,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCoachNote' : IDL.Func([CoachNote], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'completeTask' : IDL.Func([IDL.Text], [], []),
  'createAnnouncement' : IDL.Func([Announcement], [], []),
  'createFollowupTask' : IDL.Func([FollowupTask], [], []),
  'createMemberProfile' : IDL.Func([MemberProfile], [], []),
  'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'getAllCoachNotes' : IDL.Func([], [IDL.Vec(CoachNote)], ['query']),
  'getAllDailyCheckins' : IDL.Func([], [IDL.Vec(DailyCheckin)], ['query']),
  'getAllFollowupTasks' : IDL.Func([], [IDL.Vec(FollowupTask)], ['query']),
  'getAllMembers' : IDL.Func([], [IDL.Vec(MemberProfile)], ['query']),
  'getAllMessageLogs' : IDL.Func([], [IDL.Vec(MessageLog)], ['query']),
  'getAllWeeklyCheckins' : IDL.Func([], [IDL.Vec(WeeklyCheckin)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getMemberProfile' : IDL.Func([IDL.Text], [MemberProfile], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logMessage' : IDL.Func([MessageLog], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitDailyCheckin' : IDL.Func([DailyCheckin], [], []),
  'submitWeeklyCheckin' : IDL.Func([WeeklyCheckin], [], []),
  'updateMemberProfile' : IDL.Func([IDL.Text, MemberProfile], [], []),
  'updateTaskStatus' : IDL.Func([IDL.Text, TaskStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const CoachNote = IDL.Record({
    'id' : IDL.Text,
    'memberId' : IDL.Text,
    'content' : IDL.Text,
    'timestamp' : Time,
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Announcement = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'scheduledTime' : IDL.Opt(Time),
    'published' : IDL.Bool,
    'image' : IDL.Opt(ExternalBlob),
    'targetSegment' : IDL.Text,
  });
  const TaskStatus = IDL.Variant({
    'completed' : IDL.Null,
    'dueToday' : IDL.Null,
    'overdue' : IDL.Null,
  });
  const FollowupTask = IDL.Record({
    'id' : IDL.Text,
    'status' : TaskStatus,
    'memberId' : IDL.Text,
    'completionDate' : IDL.Opt(Time),
    'dueDate' : Time,
    'description' : IDL.Text,
    'coachNoteId' : IDL.Opt(IDL.Text),
  });
  const ConsentStatus = IDL.Variant({
    'active' : IDL.Null,
    'pending' : IDL.Null,
    'optedOut' : IDL.Null,
  });
  const ReminderPreference = IDL.Variant({
    'both' : IDL.Null,
    'none' : IDL.Null,
    'daily' : IDL.Null,
    'weekly' : IDL.Null,
  });
  const Gender = IDL.Variant({
    'other' : IDL.Null,
    'female' : IDL.Null,
    'male' : IDL.Null,
  });
  const MemberProfile = IDL.Record({
    'id' : IDL.Text,
    'age' : IDL.Nat,
    'trfWindowEnd' : IDL.Opt(Time),
    'consentStatus' : ConsentStatus,
    'heightCm' : IDL.Float64,
    'name' : IDL.Text,
    'consentTimestamp' : IDL.Opt(Time),
    'noSnacks' : IDL.Bool,
    'reminderPreference' : ReminderPreference,
    'startingWeight' : IDL.Float64,
    'waistCircumference' : IDL.Opt(IDL.Float64),
    'targetDate' : IDL.Opt(Time),
    'chestCircumference' : IDL.Opt(IDL.Float64),
    'gender' : Gender,
    'targetWeight' : IDL.Opt(IDL.Float64),
    'programType' : IDL.Text,
    'hipCircumference' : IDL.Opt(IDL.Float64),
    'trfWindowStart' : IDL.Opt(Time),
    'whatsappPhone' : IDL.Text,
    'currentWeight' : IDL.Float64,
  });
  const DailyCheckin = IDL.Record({
    'id' : IDL.Text,
    'memberId' : IDL.Text,
    'waterIntake' : IDL.Float64,
    'date' : Time,
    'digestionScore' : IDL.Nat,
    'steps' : IDL.Nat,
    'notes' : IDL.Opt(IDL.Text),
    'moodScore' : IDL.Nat,
    'workoutMinutes' : IDL.Nat,
    'complianceScore' : IDL.Nat,
    'sleepHours' : IDL.Float64,
  });
  const MessageLog = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'memberId' : IDL.Text,
    'templateId' : IDL.Text,
    'timestamp' : Time,
    'providerMessageId' : IDL.Opt(IDL.Text),
  });
  const WeeklyCheckin = IDL.Record({
    'id' : IDL.Text,
    'hip' : IDL.Opt(IDL.Float64),
    'weight' : IDL.Float64,
    'memberId' : IDL.Text,
    'date' : Time,
    'chest' : IDL.Opt(IDL.Float64),
    'wins' : IDL.Opt(IDL.Text),
    'struggles' : IDL.Opt(IDL.Text),
    'waist' : IDL.Opt(IDL.Float64),
    'photos' : IDL.Opt(ExternalBlob),
  });
  const UserRole = IDL.Variant({
    'member' : IDL.Null,
    'assistantCoach' : IDL.Null,
    'coach' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'memberId' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'role' : UserRole,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCoachNote' : IDL.Func([CoachNote], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'completeTask' : IDL.Func([IDL.Text], [], []),
    'createAnnouncement' : IDL.Func([Announcement], [], []),
    'createFollowupTask' : IDL.Func([FollowupTask], [], []),
    'createMemberProfile' : IDL.Func([MemberProfile], [], []),
    'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'getAllCoachNotes' : IDL.Func([], [IDL.Vec(CoachNote)], ['query']),
    'getAllDailyCheckins' : IDL.Func([], [IDL.Vec(DailyCheckin)], ['query']),
    'getAllFollowupTasks' : IDL.Func([], [IDL.Vec(FollowupTask)], ['query']),
    'getAllMembers' : IDL.Func([], [IDL.Vec(MemberProfile)], ['query']),
    'getAllMessageLogs' : IDL.Func([], [IDL.Vec(MessageLog)], ['query']),
    'getAllWeeklyCheckins' : IDL.Func([], [IDL.Vec(WeeklyCheckin)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getMemberProfile' : IDL.Func([IDL.Text], [MemberProfile], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logMessage' : IDL.Func([MessageLog], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitDailyCheckin' : IDL.Func([DailyCheckin], [], []),
    'submitWeeklyCheckin' : IDL.Func([WeeklyCheckin], [], []),
    'updateMemberProfile' : IDL.Func([IDL.Text, MemberProfile], [], []),
    'updateTaskStatus' : IDL.Func([IDL.Text, TaskStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };