/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface WeeklyCheckin {
    id: string;
    hip?: number;
    weight: number;
    memberId: string;
    date: Time;
    chest?: number;
    wins?: string;
    struggles?: string;
    waist?: number;
    photos?: ExternalBlob;
}
export interface DailyCheckin {
    id: string;
    memberId: string;
    waterIntake: number;
    date: Time;
    digestionScore: bigint;
    steps: bigint;
    notes?: string;
    moodScore: bigint;
    workoutMinutes: bigint;
    complianceScore: bigint;
    sleepHours: number;
}
export type Time = bigint;
export interface UpdateWeightInput {
    memberId: string;
    newWeight: number;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface MessageLog {
    id: string;
    status: string;
    memberId: string;
    templateId: string;
    timestamp: Time;
    providerMessageId?: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface MemberProfile {
    id: string;
    age: bigint;
    trfWindowEnd?: Time;
    consentStatus: ConsentStatus;
    heightCm: number;
    lastWeightUpdate?: Time;
    name: string;
    consentTimestamp?: Time;
    noSnacks: boolean;
    reminderPreference: ReminderPreference;
    startingWeight: number;
    waistCircumference?: number;
    targetDate?: Time;
    chestCircumference?: number;
    gender: Gender;
    targetWeight?: number;
    programType: string;
    hipCircumference?: number;
    trfWindowStart?: Time;
    whatsappPhone: string;
    currentWeight: number;
}
export interface Announcement {
    id: string;
    title: string;
    content: string;
    scheduledTime?: Time;
    published: boolean;
    image?: ExternalBlob;
    targetSegment: string;
}
export interface SwitchMemberInput {
    whatsappPhone: string;
}
export interface CoachNote {
    id: string;
    memberId: string;
    content: string;
    timestamp: Time;
}
export interface FollowupTask {
    id: string;
    status: TaskStatus;
    memberId: string;
    completionDate?: Time;
    dueDate: Time;
    description: string;
    coachNoteId?: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfile {
    memberId?: string;
    name: string;
    role: UserRole;
}
export enum ConsentStatus {
    active = "active",
    pending = "pending",
    optedOut = "optedOut"
}
export enum Gender {
    other = "other",
    female = "female",
    male = "male"
}
export enum ReminderPreference {
    both = "both",
    none = "none",
    daily = "daily",
    weekly = "weekly"
}
export enum TaskStatus {
    completed = "completed",
    dueToday = "dueToday",
    overdue = "overdue"
}
export enum UserRole {
    member = "member",
    assistantCoach = "assistantCoach",
    coach = "coach"
}
export enum UserRole__1 {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCoachNote(note: CoachNote): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole__1): Promise<void>;
    completeTask(id: string): Promise<void>;
    createAnnouncement(announcement: Announcement): Promise<void>;
    createFollowupTask(task: FollowupTask): Promise<void>;
    createMemberProfile(profile: MemberProfile): Promise<void>;
    getAllAnnouncements(): Promise<Array<Announcement>>;
    getAllCoachNotes(): Promise<Array<CoachNote>>;
    getAllDailyCheckins(): Promise<Array<DailyCheckin>>;
    getAllFollowupTasks(): Promise<Array<FollowupTask>>;
    getAllMembers(): Promise<Array<MemberProfile>>;
    getAllMessageLogs(): Promise<Array<MessageLog>>;
    getAllWeeklyCheckins(): Promise<Array<WeeklyCheckin>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole__1>;
    getMemberProfile(id: string): Promise<MemberProfile>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    logMessage(log: MessageLog): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitDailyCheckin(checkin: DailyCheckin): Promise<void>;
    submitWeeklyCheckin(checkin: WeeklyCheckin): Promise<void>;
    switchMember(params: SwitchMemberInput): Promise<UserProfile | null>;
    updateCurrentWeight(input: UpdateWeightInput): Promise<void>;
    updateMemberProfile(id: string, profile: MemberProfile): Promise<void>;
    updateTaskStatus(id: string, status: TaskStatus): Promise<void>;
}
import type { Announcement as _Announcement, ConsentStatus as _ConsentStatus, DailyCheckin as _DailyCheckin, ExternalBlob as _ExternalBlob, FollowupTask as _FollowupTask, Gender as _Gender, MemberProfile as _MemberProfile, MessageLog as _MessageLog, ReminderPreference as _ReminderPreference, TaskStatus as _TaskStatus, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, UserRole__1 as _UserRole__1, WeeklyCheckin as _WeeklyCheckin, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCoachNote(arg0: CoachNote): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCoachNote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCoachNote(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async completeTask(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeTask(arg0);
            return result;
        }
    }
    async createAnnouncement(arg0: Announcement): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createAnnouncement(await to_candid_Announcement_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAnnouncement(await to_candid_Announcement_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createFollowupTask(arg0: FollowupTask): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createFollowupTask(to_candid_FollowupTask_n13(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFollowupTask(to_candid_FollowupTask_n13(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createMemberProfile(arg0: MemberProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createMemberProfile(to_candid_MemberProfile_n17(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMemberProfile(to_candid_MemberProfile_n17(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getAllAnnouncements(): Promise<Array<Announcement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAnnouncements();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAnnouncements();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllCoachNotes(): Promise<Array<CoachNote>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCoachNotes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCoachNotes();
            return result;
        }
    }
    async getAllDailyCheckins(): Promise<Array<DailyCheckin>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDailyCheckins();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDailyCheckins();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllFollowupTasks(): Promise<Array<FollowupTask>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFollowupTasks();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFollowupTasks();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMembers(): Promise<Array<MemberProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMembers();
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMembers();
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMessageLogs(): Promise<Array<MessageLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMessageLogs();
                return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMessageLogs();
            return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllWeeklyCheckins(): Promise<Array<WeeklyCheckin>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWeeklyCheckins();
                return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWeeklyCheckins();
            return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole__1_n61(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole__1_n61(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMemberProfile(arg0: string): Promise<MemberProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getMemberProfile(arg0);
                return from_candid_MemberProfile_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMemberProfile(arg0);
            return from_candid_MemberProfile_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async logMessage(arg0: MessageLog): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logMessage(to_candid_MessageLog_n63(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logMessage(to_candid_MessageLog_n63(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n65(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n65(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitDailyCheckin(arg0: DailyCheckin): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitDailyCheckin(to_candid_DailyCheckin_n69(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitDailyCheckin(to_candid_DailyCheckin_n69(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitWeeklyCheckin(arg0: WeeklyCheckin): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitWeeklyCheckin(await to_candid_WeeklyCheckin_n71(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitWeeklyCheckin(await to_candid_WeeklyCheckin_n71(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async switchMember(arg0: SwitchMemberInput): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.switchMember(arg0);
                return from_candid_opt_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.switchMember(arg0);
            return from_candid_opt_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateCurrentWeight(arg0: UpdateWeightInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCurrentWeight(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCurrentWeight(arg0);
            return result;
        }
    }
    async updateMemberProfile(arg0: string, arg1: MemberProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMemberProfile(arg0, to_candid_MemberProfile_n17(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMemberProfile(arg0, to_candid_MemberProfile_n17(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateTaskStatus(arg0: string, arg1: TaskStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTaskStatus(arg0, to_candid_TaskStatus_n15(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTaskStatus(arg0, to_candid_TaskStatus_n15(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
async function from_candid_Announcement_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Announcement): Promise<Announcement> {
    return await from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_ConsentStatus_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ConsentStatus): ConsentStatus {
    return from_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function from_candid_DailyCheckin_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DailyCheckin): DailyCheckin {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_FollowupTask_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FollowupTask): FollowupTask {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_Gender_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Gender): Gender {
    return from_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function from_candid_MemberProfile_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MemberProfile): MemberProfile {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_MessageLog_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MessageLog): MessageLog {
    return from_candid_record_n52(_uploadFile, _downloadFile, value);
}
function from_candid_ReminderPreference_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReminderPreference): ReminderPreference {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid_TaskStatus_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskStatus): TaskStatus {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n58(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole__1_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole__1): UserRole__1 {
    return from_candid_variant_n62(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n60(_uploadFile, _downloadFile, value);
}
async function from_candid_WeeklyCheckin_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WeeklyCheckin): Promise<WeeklyCheckin> {
    return await from_candid_record_n55(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n30(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n57(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    content: string;
    scheduledTime: [] | [_Time];
    published: boolean;
    image: [] | [_ExternalBlob];
    targetSegment: string;
}): Promise<{
    id: string;
    title: string;
    content: string;
    scheduledTime?: Time;
    published: boolean;
    image?: ExternalBlob;
    targetSegment: string;
}> {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        scheduledTime: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.scheduledTime)),
        published: value.published,
        image: record_opt_to_undefined(await from_candid_opt_n29(_uploadFile, _downloadFile, value.image)),
        targetSegment: value.targetSegment
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    memberId: string;
    waterIntake: number;
    date: _Time;
    digestionScore: bigint;
    steps: bigint;
    notes: [] | [string];
    moodScore: bigint;
    workoutMinutes: bigint;
    complianceScore: bigint;
    sleepHours: number;
}): {
    id: string;
    memberId: string;
    waterIntake: number;
    date: Time;
    digestionScore: bigint;
    steps: bigint;
    notes?: string;
    moodScore: bigint;
    workoutMinutes: bigint;
    complianceScore: bigint;
    sleepHours: number;
} {
    return {
        id: value.id,
        memberId: value.memberId,
        waterIntake: value.waterIntake,
        date: value.date,
        digestionScore: value.digestionScore,
        steps: value.steps,
        notes: record_opt_to_undefined(from_candid_opt_n34(_uploadFile, _downloadFile, value.notes)),
        moodScore: value.moodScore,
        workoutMinutes: value.workoutMinutes,
        complianceScore: value.complianceScore,
        sleepHours: value.sleepHours
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _TaskStatus;
    memberId: string;
    completionDate: [] | [_Time];
    dueDate: _Time;
    description: string;
    coachNoteId: [] | [string];
}): {
    id: string;
    status: TaskStatus;
    memberId: string;
    completionDate?: Time;
    dueDate: Time;
    description: string;
    coachNoteId?: string;
} {
    return {
        id: value.id,
        status: from_candid_TaskStatus_n38(_uploadFile, _downloadFile, value.status),
        memberId: value.memberId,
        completionDate: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.completionDate)),
        dueDate: value.dueDate,
        description: value.description,
        coachNoteId: record_opt_to_undefined(from_candid_opt_n34(_uploadFile, _downloadFile, value.coachNoteId))
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    age: bigint;
    trfWindowEnd: [] | [_Time];
    consentStatus: _ConsentStatus;
    heightCm: number;
    lastWeightUpdate: [] | [_Time];
    name: string;
    consentTimestamp: [] | [_Time];
    noSnacks: boolean;
    reminderPreference: _ReminderPreference;
    startingWeight: number;
    waistCircumference: [] | [number];
    targetDate: [] | [_Time];
    chestCircumference: [] | [number];
    gender: _Gender;
    targetWeight: [] | [number];
    programType: string;
    hipCircumference: [] | [number];
    trfWindowStart: [] | [_Time];
    whatsappPhone: string;
    currentWeight: number;
}): {
    id: string;
    age: bigint;
    trfWindowEnd?: Time;
    consentStatus: ConsentStatus;
    heightCm: number;
    lastWeightUpdate?: Time;
    name: string;
    consentTimestamp?: Time;
    noSnacks: boolean;
    reminderPreference: ReminderPreference;
    startingWeight: number;
    waistCircumference?: number;
    targetDate?: Time;
    chestCircumference?: number;
    gender: Gender;
    targetWeight?: number;
    programType: string;
    hipCircumference?: number;
    trfWindowStart?: Time;
    whatsappPhone: string;
    currentWeight: number;
} {
    return {
        id: value.id,
        age: value.age,
        trfWindowEnd: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.trfWindowEnd)),
        consentStatus: from_candid_ConsentStatus_n43(_uploadFile, _downloadFile, value.consentStatus),
        heightCm: value.heightCm,
        lastWeightUpdate: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.lastWeightUpdate)),
        name: value.name,
        consentTimestamp: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.consentTimestamp)),
        noSnacks: value.noSnacks,
        reminderPreference: from_candid_ReminderPreference_n45(_uploadFile, _downloadFile, value.reminderPreference),
        startingWeight: value.startingWeight,
        waistCircumference: record_opt_to_undefined(from_candid_opt_n47(_uploadFile, _downloadFile, value.waistCircumference)),
        targetDate: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.targetDate)),
        chestCircumference: record_opt_to_undefined(from_candid_opt_n47(_uploadFile, _downloadFile, value.chestCircumference)),
        gender: from_candid_Gender_n48(_uploadFile, _downloadFile, value.gender),
        targetWeight: record_opt_to_undefined(from_candid_opt_n47(_uploadFile, _downloadFile, value.targetWeight)),
        programType: value.programType,
        hipCircumference: record_opt_to_undefined(from_candid_opt_n47(_uploadFile, _downloadFile, value.hipCircumference)),
        trfWindowStart: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.trfWindowStart)),
        whatsappPhone: value.whatsappPhone,
        currentWeight: value.currentWeight
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: string;
    memberId: string;
    templateId: string;
    timestamp: _Time;
    providerMessageId: [] | [string];
}): {
    id: string;
    status: string;
    memberId: string;
    templateId: string;
    timestamp: Time;
    providerMessageId?: string;
} {
    return {
        id: value.id,
        status: value.status,
        memberId: value.memberId,
        templateId: value.templateId,
        timestamp: value.timestamp,
        providerMessageId: record_opt_to_undefined(from_candid_opt_n34(_uploadFile, _downloadFile, value.providerMessageId))
    };
}
async function from_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    hip: [] | [number];
    weight: number;
    memberId: string;
    date: _Time;
    chest: [] | [number];
    wins: [] | [string];
    struggles: [] | [string];
    waist: [] | [number];
    photos: [] | [_ExternalBlob];
}): Promise<{
    id: string;
    hip?: number;
    weight: number;
    memberId: string;
    date: Time;
    chest?: number;
    wins?: string;
    struggles?: string;
    waist?: number;
    photos?: ExternalBlob;
}> {
    return {
        id: value.id,
        hip: record_opt_to_undefined(from_candid_opt_n47(_uploadFile, _downloadFile, value.hip)),
        weight: value.weight,
        memberId: value.memberId,
        date: value.date,
        chest: record_opt_to_undefined(from_candid_opt_n47(_uploadFile, _downloadFile, value.chest)),
        wins: record_opt_to_undefined(from_candid_opt_n34(_uploadFile, _downloadFile, value.wins)),
        struggles: record_opt_to_undefined(from_candid_opt_n34(_uploadFile, _downloadFile, value.struggles)),
        waist: record_opt_to_undefined(from_candid_opt_n47(_uploadFile, _downloadFile, value.waist)),
        photos: record_opt_to_undefined(await from_candid_opt_n29(_uploadFile, _downloadFile, value.photos))
    };
}
function from_candid_record_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    memberId: [] | [string];
    name: string;
    role: _UserRole;
}): {
    memberId?: string;
    name: string;
    role: UserRole;
} {
    return {
        memberId: record_opt_to_undefined(from_candid_opt_n34(_uploadFile, _downloadFile, value.memberId)),
        name: value.name,
        role: from_candid_UserRole_n59(_uploadFile, _downloadFile, value.role)
    };
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: null;
} | {
    dueToday: null;
} | {
    overdue: null;
}): TaskStatus {
    return "completed" in value ? TaskStatus.completed : "dueToday" in value ? TaskStatus.dueToday : "overdue" in value ? TaskStatus.overdue : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    pending: null;
} | {
    optedOut: null;
}): ConsentStatus {
    return "active" in value ? ConsentStatus.active : "pending" in value ? ConsentStatus.pending : "optedOut" in value ? ConsentStatus.optedOut : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    both: null;
} | {
    none: null;
} | {
    daily: null;
} | {
    weekly: null;
}): ReminderPreference {
    return "both" in value ? ReminderPreference.both : "none" in value ? ReminderPreference.none : "daily" in value ? ReminderPreference.daily : "weekly" in value ? ReminderPreference.weekly : value;
}
function from_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    female: null;
} | {
    male: null;
}): Gender {
    return "other" in value ? Gender.other : "female" in value ? Gender.female : "male" in value ? Gender.male : value;
}
function from_candid_variant_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    member: null;
} | {
    assistantCoach: null;
} | {
    coach: null;
}): UserRole {
    return "member" in value ? UserRole.member : "assistantCoach" in value ? UserRole.assistantCoach : "coach" in value ? UserRole.coach : value;
}
function from_candid_variant_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole__1 {
    return "admin" in value ? UserRole__1.admin : "user" in value ? UserRole__1.user : "guest" in value ? UserRole__1.guest : value;
}
async function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Announcement>): Promise<Array<Announcement>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Announcement_n26(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DailyCheckin>): Array<DailyCheckin> {
    return value.map((x)=>from_candid_DailyCheckin_n32(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FollowupTask>): Array<FollowupTask> {
    return value.map((x)=>from_candid_FollowupTask_n36(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MemberProfile>): Array<MemberProfile> {
    return value.map((x)=>from_candid_MemberProfile_n41(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MessageLog>): Array<MessageLog> {
    return value.map((x)=>from_candid_MessageLog_n51(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WeeklyCheckin>): Promise<Array<WeeklyCheckin>> {
    return await Promise.all(value.map(async (x)=>await from_candid_WeeklyCheckin_n54(_uploadFile, _downloadFile, x)));
}
async function to_candid_Announcement_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Announcement): Promise<_Announcement> {
    return await to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_ConsentStatus_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ConsentStatus): _ConsentStatus {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_DailyCheckin_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DailyCheckin): _DailyCheckin {
    return to_candid_record_n70(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_FollowupTask_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FollowupTask): _FollowupTask {
    return to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_Gender_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): _Gender {
    return to_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function to_candid_MemberProfile_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MemberProfile): _MemberProfile {
    return to_candid_record_n18(_uploadFile, _downloadFile, value);
}
function to_candid_MessageLog_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MessageLog): _MessageLog {
    return to_candid_record_n64(_uploadFile, _downloadFile, value);
}
function to_candid_ReminderPreference_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReminderPreference): _ReminderPreference {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_TaskStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskStatus): _TaskStatus {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n66(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole__1_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): _UserRole__1 {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n68(_uploadFile, _downloadFile, value);
}
async function to_candid_WeeklyCheckin_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WeeklyCheckin): Promise<_WeeklyCheckin> {
    return await to_candid_record_n72(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    content: string;
    scheduledTime?: Time;
    published: boolean;
    image?: ExternalBlob;
    targetSegment: string;
}): Promise<{
    id: string;
    title: string;
    content: string;
    scheduledTime: [] | [_Time];
    published: boolean;
    image: [] | [_ExternalBlob];
    targetSegment: string;
}> {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        scheduledTime: value.scheduledTime ? candid_some(value.scheduledTime) : candid_none(),
        published: value.published,
        image: value.image ? candid_some(await to_candid_ExternalBlob_n12(_uploadFile, _downloadFile, value.image)) : candid_none(),
        targetSegment: value.targetSegment
    };
}
function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: TaskStatus;
    memberId: string;
    completionDate?: Time;
    dueDate: Time;
    description: string;
    coachNoteId?: string;
}): {
    id: string;
    status: _TaskStatus;
    memberId: string;
    completionDate: [] | [_Time];
    dueDate: _Time;
    description: string;
    coachNoteId: [] | [string];
} {
    return {
        id: value.id,
        status: to_candid_TaskStatus_n15(_uploadFile, _downloadFile, value.status),
        memberId: value.memberId,
        completionDate: value.completionDate ? candid_some(value.completionDate) : candid_none(),
        dueDate: value.dueDate,
        description: value.description,
        coachNoteId: value.coachNoteId ? candid_some(value.coachNoteId) : candid_none()
    };
}
function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    age: bigint;
    trfWindowEnd?: Time;
    consentStatus: ConsentStatus;
    heightCm: number;
    lastWeightUpdate?: Time;
    name: string;
    consentTimestamp?: Time;
    noSnacks: boolean;
    reminderPreference: ReminderPreference;
    startingWeight: number;
    waistCircumference?: number;
    targetDate?: Time;
    chestCircumference?: number;
    gender: Gender;
    targetWeight?: number;
    programType: string;
    hipCircumference?: number;
    trfWindowStart?: Time;
    whatsappPhone: string;
    currentWeight: number;
}): {
    id: string;
    age: bigint;
    trfWindowEnd: [] | [_Time];
    consentStatus: _ConsentStatus;
    heightCm: number;
    lastWeightUpdate: [] | [_Time];
    name: string;
    consentTimestamp: [] | [_Time];
    noSnacks: boolean;
    reminderPreference: _ReminderPreference;
    startingWeight: number;
    waistCircumference: [] | [number];
    targetDate: [] | [_Time];
    chestCircumference: [] | [number];
    gender: _Gender;
    targetWeight: [] | [number];
    programType: string;
    hipCircumference: [] | [number];
    trfWindowStart: [] | [_Time];
    whatsappPhone: string;
    currentWeight: number;
} {
    return {
        id: value.id,
        age: value.age,
        trfWindowEnd: value.trfWindowEnd ? candid_some(value.trfWindowEnd) : candid_none(),
        consentStatus: to_candid_ConsentStatus_n19(_uploadFile, _downloadFile, value.consentStatus),
        heightCm: value.heightCm,
        lastWeightUpdate: value.lastWeightUpdate ? candid_some(value.lastWeightUpdate) : candid_none(),
        name: value.name,
        consentTimestamp: value.consentTimestamp ? candid_some(value.consentTimestamp) : candid_none(),
        noSnacks: value.noSnacks,
        reminderPreference: to_candid_ReminderPreference_n21(_uploadFile, _downloadFile, value.reminderPreference),
        startingWeight: value.startingWeight,
        waistCircumference: value.waistCircumference ? candid_some(value.waistCircumference) : candid_none(),
        targetDate: value.targetDate ? candid_some(value.targetDate) : candid_none(),
        chestCircumference: value.chestCircumference ? candid_some(value.chestCircumference) : candid_none(),
        gender: to_candid_Gender_n23(_uploadFile, _downloadFile, value.gender),
        targetWeight: value.targetWeight ? candid_some(value.targetWeight) : candid_none(),
        programType: value.programType,
        hipCircumference: value.hipCircumference ? candid_some(value.hipCircumference) : candid_none(),
        trfWindowStart: value.trfWindowStart ? candid_some(value.trfWindowStart) : candid_none(),
        whatsappPhone: value.whatsappPhone,
        currentWeight: value.currentWeight
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: string;
    memberId: string;
    templateId: string;
    timestamp: Time;
    providerMessageId?: string;
}): {
    id: string;
    status: string;
    memberId: string;
    templateId: string;
    timestamp: _Time;
    providerMessageId: [] | [string];
} {
    return {
        id: value.id,
        status: value.status,
        memberId: value.memberId,
        templateId: value.templateId,
        timestamp: value.timestamp,
        providerMessageId: value.providerMessageId ? candid_some(value.providerMessageId) : candid_none()
    };
}
function to_candid_record_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    memberId?: string;
    name: string;
    role: UserRole;
}): {
    memberId: [] | [string];
    name: string;
    role: _UserRole;
} {
    return {
        memberId: value.memberId ? candid_some(value.memberId) : candid_none(),
        name: value.name,
        role: to_candid_UserRole_n67(_uploadFile, _downloadFile, value.role)
    };
}
function to_candid_record_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    memberId: string;
    waterIntake: number;
    date: Time;
    digestionScore: bigint;
    steps: bigint;
    notes?: string;
    moodScore: bigint;
    workoutMinutes: bigint;
    complianceScore: bigint;
    sleepHours: number;
}): {
    id: string;
    memberId: string;
    waterIntake: number;
    date: _Time;
    digestionScore: bigint;
    steps: bigint;
    notes: [] | [string];
    moodScore: bigint;
    workoutMinutes: bigint;
    complianceScore: bigint;
    sleepHours: number;
} {
    return {
        id: value.id,
        memberId: value.memberId,
        waterIntake: value.waterIntake,
        date: value.date,
        digestionScore: value.digestionScore,
        steps: value.steps,
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        moodScore: value.moodScore,
        workoutMinutes: value.workoutMinutes,
        complianceScore: value.complianceScore,
        sleepHours: value.sleepHours
    };
}
async function to_candid_record_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    hip?: number;
    weight: number;
    memberId: string;
    date: Time;
    chest?: number;
    wins?: string;
    struggles?: string;
    waist?: number;
    photos?: ExternalBlob;
}): Promise<{
    id: string;
    hip: [] | [number];
    weight: number;
    memberId: string;
    date: _Time;
    chest: [] | [number];
    wins: [] | [string];
    struggles: [] | [string];
    waist: [] | [number];
    photos: [] | [_ExternalBlob];
}> {
    return {
        id: value.id,
        hip: value.hip ? candid_some(value.hip) : candid_none(),
        weight: value.weight,
        memberId: value.memberId,
        date: value.date,
        chest: value.chest ? candid_some(value.chest) : candid_none(),
        wins: value.wins ? candid_some(value.wins) : candid_none(),
        struggles: value.struggles ? candid_some(value.struggles) : candid_none(),
        waist: value.waist ? candid_some(value.waist) : candid_none(),
        photos: value.photos ? candid_some(await to_candid_ExternalBlob_n12(_uploadFile, _downloadFile, value.photos)) : candid_none()
    };
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskStatus): {
    completed: null;
} | {
    dueToday: null;
} | {
    overdue: null;
} {
    return value == TaskStatus.completed ? {
        completed: null
    } : value == TaskStatus.dueToday ? {
        dueToday: null
    } : value == TaskStatus.overdue ? {
        overdue: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ConsentStatus): {
    active: null;
} | {
    pending: null;
} | {
    optedOut: null;
} {
    return value == ConsentStatus.active ? {
        active: null
    } : value == ConsentStatus.pending ? {
        pending: null
    } : value == ConsentStatus.optedOut ? {
        optedOut: null
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReminderPreference): {
    both: null;
} | {
    none: null;
} | {
    daily: null;
} | {
    weekly: null;
} {
    return value == ReminderPreference.both ? {
        both: null
    } : value == ReminderPreference.none ? {
        none: null
    } : value == ReminderPreference.daily ? {
        daily: null
    } : value == ReminderPreference.weekly ? {
        weekly: null
    } : value;
}
function to_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): {
    other: null;
} | {
    female: null;
} | {
    male: null;
} {
    return value == Gender.other ? {
        other: null
    } : value == Gender.female ? {
        female: null
    } : value == Gender.male ? {
        male: null
    } : value;
}
function to_candid_variant_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    member: null;
} | {
    assistantCoach: null;
} | {
    coach: null;
} {
    return value == UserRole.member ? {
        member: null
    } : value == UserRole.assistantCoach ? {
        assistantCoach: null
    } : value == UserRole.coach ? {
        coach: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole__1.admin ? {
        admin: null
    } : value == UserRole__1.user ? {
        user: null
    } : value == UserRole__1.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
